```{r}
library(tidyverse)
library(tidymodels)
library(e1071)
library(ROCR)
```

```{r}
parole <- read_csv("parole.csv")
```
```{r}
str(parole)
summary(parole)
```


```{r}
parole = parole %>% mutate(male = as_factor(male)) %>% 
  mutate(male = fct_recode(male, "female" = "0", "male" = "1" )) %>%
  mutate(race = as_factor(race)) %>%
 mutate(race = fct_recode(race, "otherwise" = "2", "white" = "1" ))%>%

 mutate(state = as_factor(state)) %>%
  mutate(state = fct_recode(state, "Kentucky" = "2", "Louisiana" = "3", "Virginia" = "4", OtherStates = "1" ))%>%
  
mutate(crime = as_factor(crime)) %>%
mutate(crime = fct_recode(crime, "Lareceny" = "2", "DrugRelated" = "3", "DrivingRelated" = "4", "OtherCrimes" = "1" ))%>%
mutate(multiple.offenses = as_factor(multiple.offenses)) %>% 
  mutate(multiple.offenses = fct_recode(multiple.offenses, "MultipleOffenses" = "1", "Otherwise" = "0"))%>%
 
  mutate(violator = as_factor(violator))%>% 
mutate(violator = fct_recode(violator, "ViolatedParole" = "1", "NoViolations" = "0" ))

str(parole)
summary(parole)

```  

```{r}
set.seed(12345)
parole_split = initial_split(parole, prop = 0.70, strata = violator)
train = training(parole_split)
test = testing(parole_split)
```

```{r}
train = train %>% mutate(violator = fct_relevel(violator, c("NoViolations","ViolatedParole")))
levels(train$violator)
```

```{r}
parole_model = 
  logistic_reg(mode = "classification") %>% #note the use of logistic_reg
  set_engine("glm") #standard logistic regression engine is glm

parole_recipe = recipe(violator~ state +  multiple.offenses +race, train) %>%
  step_dummy(all_nominal(), -all_outcomes()) #exclude the response variable from being dummy converted  

logreg_wf = workflow() %>%
  add_recipe(parole_recipe) %>% 
  add_model(parole_model)

parole_fit = fit(logreg_wf, train)
```

```{r}
summary(parole_fit$fit$fit$fit)
```

```{r 9}
newdata = data.frame(state = "Louisiana", multiple.offenses = "MultipleOffenses", race = "white")
predict(parole_fit, newdata, type="prob")
```

```{r}
predictions = predict(parole_fit, train, type="prob")
```



```{r}
predictions = predict(parole_fit,train, type = "prob")[2]
head(predictions)
```


```{r}
ROCRpred = prediction(predictions, train$violator) 

ROCRperf = performance(ROCRpred, "tpr", "fpr")
plot(ROCRperf, colorize=TRUE, print.cutoffs.at=seq(0,1,by=0.1), text.adj=c(-0.2,1.7))
```
```{r}
opt.cut = function(perf, pred){
    cut.ind = mapply(FUN=function(x, y, p){
        d = (x - 0)^2 + (y-1)^2
        ind = which(d == min(d))
        c(sensitivity = y[[ind]], specificity = 1-x[[ind]], 
            cutoff = p[[ind]])
    }, perf@x.values, perf@y.values, pred@cutoffs)
}
print(opt.cut(ROCRperf, ROCRpred))
```
```{r}
t1 = table(train$violator,predictions > 0.2015788)
t1
```
```{r}
36/(18+36)

```




```{r}
(t1[1,1]+t1[2,2])/nrow(train)
```
```{r}
t1 = table(train$violator,predictions > 0.2)
t1
(t1[1,1]+t1[2,2])/nrow(train)
```
```{r}
predictions = predict(parole_fit,test, type = "prob")[2]
t1 = table(test$violator,predictions > 0.5)
t1
(t1[1,1]+t1[2,2])/nrow(test)
```

