```{r}
library(tidyverse)
library(tidymodels)
library(GGally)
library(lmtest)
```
```{r}
air = airquality
```

```{r}
summary(air)
```
```{r}
ggpairs(air)
```

```{r}
air2 = air %>% drop_na()
```
```{r}
ggpairs(air2)
```

```{r}
library(esquisse)
```

```{r}
esquisser(air2)
```
```{r}
ggplot(air2) +
  aes(x = Temp, y = Ozone) +
  geom_point(shape = "circle", size = 1.5, colour = "#112446") +
  theme_minimal()

```
```{r}
mod1 = lm(Ozone ~ Temp, air2) #create linear regression model
summary(mod1)
```

```{r}
weather_simple = recipe(Ozone ~ Temp, air2)
```


```{r}
lm_model = #give the model type a name 
  linear_reg() %>% #specify that we are doing linear regression
  set_engine("lm")
```

```{r}
lm_wflow = 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(weather_simple)
```

```{r}
lm_fit = fit(lm_wflow, air2)
```
```{r}
confint(lm_fit$fit$fit$fit)
```
```{r}
testdata = data.frame(Temp = c(80))
predict(lm_fit, new_data = testdata)
```
```{r}
dwtest(lm_fit$fit$fit$fit)
```

