```{r}
library(tidyverse)
library(tidymodels)
library(rpart) #for classification trees
library(rpart.plot) #plotting trees
library(RColorBrewer) #better visualization of classification trees
library(rattle) #better visualization of classification trees
library(caret) #for easy confusion matrix creation 
```

```{r}
library(readr)
heart_disease_1 <- read_csv("heart_disease-1.csv")
```

```{r}
str(heart_disease_1)
summary(heart_disease_1)
```




```{r}
heart_disease_2 = heart_disease_1 %>% mutate(ChestPainType = as_factor(ChestPainType)) %>% 
mutate(RestingECG = as_factor(RestingECG)) %>%   
mutate(ExerciseAngina = as_factor(ExerciseAngina)) %>% 
mutate(ST_Slope = as_factor(ST_Slope)) %>% 
mutate(HeartDisease = as_factor(HeartDisease)) %>% 
 mutate(Sex = as_factor(Sex)) %>% 
mutate(HeartDisease = fct_recode(HeartDisease, "No" = "0", "Yes" = "1" )) 

``` 

```{r}
str(heart_disease_2)
summary(heart_disease_2)
```




```{r}
set.seed(12345) 
Heart_split = initial_split(heart_disease_2, prop = 0.7, strata = HeartDisease) #70% in training
train = training(Heart_split)
test = testing(Heart_split)
```

```{r}
Heart_recipe = recipe(HeartDisease  ~.,data = train )

tree_model = decision_tree() %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

HeartDisease_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(Heart_recipe)

Heart_fit = fit(HeartDisease_wflow, train)
```


```{r}
#extract the tree's fit from the fit object
tree = Heart_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

#plot the tree
fancyRpartPlot(tree)
```
```{r}
Heart_fit$fit$fit$fit$cptable
```
```{r}
set.seed(123)
folds = vfold_cv(train, v = 5)
```


```{r}
Heart2_recipe = recipe(HeartDisease  ~.,data = train) %>%
  step_dummy(all_nominal(),-all_outcomes())

tree_model = decision_tree(cost_complexity = tune()) %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

tree_grid = grid_regular(cost_complexity(),
                          levels = 25) #try 25 sensible values for cp

Heart2_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(Heart2_recipe)

tree_res = 
  Heart2_wflow %>% 
  tune_grid(
    resamples = folds,
    grid = tree_grid
    )

tree_res
```

```{r}
tree_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) 
```
```{r}
best_tree = tree_res %>%
  select_best("accuracy")

best_tree
```  


```{r}
final_wf = 
  Heart2_wflow %>% 
  finalize_workflow(best_tree)
```


```{r}
final_fit = fit(final_wf, train)

tree = final_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

fancyRpartPlot(tree, tweak = 1.5) 
```  
```{r}
treepred = predict(final_fit, train, type = "class")
head(treepred)
```


```{r}
confusionMatrix(treepred$.pred_class,train$HeartDisease,positive="Yes")
```  


```{r}
treepred_test = predict(final_fit, test, type = "class")
head(treepred_test)
```
```{r}
confusionMatrix(treepred_test$.pred_class,test$HeartDisease,positive="Yes")
```


